var missing_externs = {};

missing_externs.deltaX;
missing_externs.deltaY;
missing_externs.wheelDeltaX;
missing_externs.wheelDeltaY;
missing_externs.deltaMode;

missing_externs.mozMovementX;
missing_externs.mozMovementY;
missing_externs.webkitMovementX;
missing_externs.webkitMovementY;

missing_externs.mozRequestPointerLock
missing_externs.webkitRequestPointerLock;

missing_externs.webkitFullscreenElement;

missing_externs.FileError;
missing_externs.resolveLocalFileSystemURL;

missing_externs.webkitGetImageDataHD;
missing_externs.webkitPutImageDataHD;
missing_externs.webkitBackingStorePixelRatio;
missing_externs.mozBackingStorePixelRatio;
missing_externs.msBackingStorePixelRatio;
missing_externs.oBackingStorePixelRatio;
missing_externs.backingStorePixelRatio;
